let m1=new Map()
m1.set(1,"java")
m1.set(2,"c++")
m1.set(3,"pytho")
m1.set(4,"c")
m1.set(1,"JavaScript")
console.log(m1)
let v1=m1.get(2)
console.log(v1)
m1.delete(3)
console.log(m1)
let f=m1.has(1)
console.log(f)
